name: Run Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: vaultwatch_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: supersecurepw
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      POSTGRES_DB: vaultwatch_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecurepw
      DATABASE_URL: postgresql://postgres:supersecurepw@localhost:5432/vaultwatch_db

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-cov

      - name: Run tests with coverage
        run: |
          # ✅ Add the root directory to PYTHONPATH
          export PYTHONPATH="$PWD"
          pytest --cov=app --cov-report=xml --disable-warnings

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}